#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DrunkSpotting.Resource", IsApplication=true)]

namespace DrunkSpotting
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default568h = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drunkspotting = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int title_treatment = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int ChoosePictureButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ChoosenImageView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int SavePictureButton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int photoList = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int pictureImageView = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int progressBar = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int refresh = 2131099652;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EditPhoto = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PictureListViewItem = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int refresh = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
